### PR TITLE
Allow using array of styles in style prop

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by ianhook** [comment]
I don't like the fact that this would not be compatible with the React Primitive version of View.

Also, I'm not sure why this is required.  Can you give an example of why you'd need this?

**Comment by mathieudutour** [comment]
I'm pretty sure that's how you use `style` in `react-native` (hence in `react-primitives`):

```js
<View style={[styles.button, styles.primary]} />
```

**Comment by jacobp100** [comment]
It already works. I just get a prop type error.

**Comment by jongold** [comment]
Sweet - closing this in favor of #9

**Comment by mathieudutour** [comment]
Hum but that's a PR and #9 is an issue

**Comment by jacobp100** [comment]
We flatten styles here:

https://github.com/airbnb/react-sketchapp/blob/master/src/components/View.js

@jongold You linked an issue, not a PR. This has actual code to fix this!

**Comment by jongold** [comment]
oh wow my bad 😅

**Pull request merged**
