### PR TITLE
Fix symbols

### PR DESCRIPTION
**Pull request by ianhook**
Turns out that #177 was already done, so I updated the docs to reflect that.

There were also 2 problems with overrides that were addressed, so the example now works as expected on v46.

This may also address #112

### CODE REVIEW

**Comment by ianhook** [comment]
I've updated the flow types here: https://github.com/darknoon/sketchapp-json-flow-types/pull/10

**Comment by kmartinezmedia** [comment]
Any updates on when this will be merged?

**Comment by ianhook** [comment]
I'm not sure what to do about the flow type requirement which is the major hold up here. Any thoughts @jongold ?

**Comment by mattborn** [comment]
Bump.

**Comment by ianhook** [comment]
So the change to sketchapp-json-flow-types has made it to master, but it hasn't been publish. Once it has, this should be ok to merge.

**Comment by mathieudutour** [comment]
merged as part of #292

**Pull request closed without merging**
