### PR TITLE
feat(inner-shadow): Add possibility to define inner shadows

### PR DESCRIPTION
**Pull request by weaintplastic**
I'd like to be able to define innerShadows. Therefore I've added the following mechanic:

Based on wether a `shadowInner` flag is provided with `styles` the generated shadow will be applied to `style.shadow` or `style.innerShadow`. Also the `_class` is calculated based on the existence of that flag.

Happy to discuss naming and if it makes sense/is possible to apply the same logic to the ImageRenderer.

### CODE REVIEW

**Comment by weaintplastic** [comment]
In order to fix flow types I've created a PR over here https://github.com/darknoon/sketchapp-json-flow-types/pull/8

**Comment by weaintplastic** [comment]
@jongold What's the preferred procedure here? Should I add a dependency on the flow types pointing to the actual commit to fix the travis builds?

**Comment by ianhook** [comment]
I'm not sure how I could use this to apply both Shadows and Inner Shadows to the same thing.  @weaintplastic, can you provide an example?

**Comment by weaintplastic** [comment]
@ianhook I totally understand that coming from React Native or React Primitive this feature might not make any sense since inner shadows are not supported there. But we're coming from a React background that does support box shadow declarations (e.g. `box-shadow: inset 1px 1px 1px 0 rgba(0, 0, 0, 0.2)`)

This pull request is not about applying both a shadow and an inner shadow to the same element but to actually support the inner shadow at all. For multiple shadow support I've created an issue over here to discuss possible solutions (https://github.com/airbnb/react-sketchapp/issues/161)

**Comment by ianhook** [comment]
Ah, it's all coming together now.

**Comment by weaintplastic** [comment]
Yeah sorry. Actually everything is part of one workflow that I'm trying to implement but all the solutions are kind of dealing with their own concerns. This is why I've splitted the pull requests into more digestible chunks.

**Comment by weaintplastic** [comment]
fyi, the PR on flow-types got merged. I expect the CI checks to turn green soon. https://github.com/darknoon/sketchapp-json-flow-types/pull/8

**Comment by weaintplastic** [comment]
Sorry, still waiting for sketchapp-json-flow-types to release a new version.

**Comment by weaintplastic** [comment]
Still waiting. Pinged the owner of sketchapp-json-flow-types again.

**Comment by ianhook** [comment]
@weaintplastic it looks like your change went out in 0.2.0?

**Comment by weaintplastic** [comment]
@ianhook oh you're right. my mistake. I didn't expect the changes to be released without the missing test cases that I've filed in another PR afterwards. (https://github.com/darknoon/sketchapp-json-flow-types/pull/9).

Seems to be all green now after I've bumped the version. Please note that the dependency is now pointing back to the original repository and not to the branch of @jongold. Since flow is not complaining I guess this is okay.

**Comment by jongold** [comment]
belated thanks, @weaintplastic  :)

@ianhook one tiny thing here that I just noticed — I've been squashing commits when I merge (via GitHub's UI). It's not a big deal, just a consistency thing to bear in mind for future :)

**Comment by ianhook** [comment]
@jongold My bad. Usually I have that defaulted to squash, so I didn't even look.

I know there's a setting to force this, if you really want to make sure everyone does it.

**Pull request merged**
