### PR TITLE
Add Simple-UI example

### PR DESCRIPTION
**Pull request by jongold**
You don't have to call `render` straight away in `onRun` functions — feel free to take time to make UI and use it to set up documents.

This shows the simplest way to make a text field and use its values to render a document.

### CODE REVIEW

**Comment by arahansen** [comment]
Where were you able to find documentation on available APIs for building this UI? Does sketch describe this in their docs?

**Comment by mathieudutour** [comment]
The [AppKit](https://developer.apple.com/documentation/appkit) and Foundation macOS APIs are available. You can read more about it here: http://developer.sketchapp.com/guides/cocoascript/

**Comment by jongold** [comment]
@arahansen this example was cobbled together from some other Sketch plugins to show the https://archetypeapp.com/ developers how they might think about a plugin using react-sketchapp, whilst sticking to common Sketch plugin patterns as much as possible.

In production* we inject webviews into Sketch & use familiar React techniques to create the UI (because I prefer using the web to Cocoa, naturally). hint: using React Primitives is cool because you can do things like rendering React Native components to a webview inside Sketch, and then to Sketch itself.

How I found documentation: months of digging through random Sketch plugin source code, bothering @mathieudutour, digging through the old Sketch developer mailing list, begging the InVision & Facebook Design Tools developers to share their secrets. Unfortunately it wasn't a well documented process at all, and I don't have time to write-up what we learned - sorry I can't be more useful :(

* we have a component browser plugin for Sketch. It evolved from [this](https://twitter.com/jongold/status/866854672421634049?lang=en); I don't have an up to date video though :(

**Comment by arahansen** [comment]
Injecting webviews sounds perfect. I think that could be a very useful showcase given the target audience of this lib (web developers).

If I found the documentation for webviews, I'd be happy to contribute an example plugin that utilizes them 😁

**Comment by mathieudutour** [comment]
shameless plug for a package that makes it easier to use webviews: https://github.com/skpm/sketch-module-web-view :)

**Comment by jaridmargolin** [comment]
I really like the concept of this...

I think based on some of the changes we have made lately to allow more flexibility in rendering single pages, I think `react-sketchapp` could be a really convenient API for authoring certain types of sketch plugins (ex: Color Palette Generator)

@mathieudutour thoughts? We should either pull the trigger on getting this finalized/merged, or we should close it out.

**Comment by mathieudutour** [comment]
I'd rather have this (and the redux) examples in other repos so we don't feel too bad about not updating them. We can still link to them in the readme or something but it would make it clear that it's just POCs

**Pull request closed without merging**
