### PR TITLE
Fix View, Text and Artboard style PropTypes to accept ordinals from StyleSheet object

### PR DESCRIPTION
**Pull request by dmeehan1968**
This PR addresses #9 partially and #242 specifically.

The validation failure is a warning not an error, but this cleans it up.  I've also added test cases for the different inputs for style (plain object, stylesheet ordinal or array of either).

NB: The PR includes some changes to unrelated code introduced by prettifier as a result of committing the affected modules.

TODO: This doesn't resolve the validation of style attributes and their values as occurs in RN.

### CODE REVIEW

**Comment by dmeehan1968** [comment]
Can anyone suggest why this failed?  Is that a CI issue or something with the code?  There appears to be no log output from the failed run.

**Comment by larsonjj** [comment]
Hey @dmeehan1968,
Looks like a timeout from TravisCI. I just restarted the build to see if that works.

Great work on this BTW 👍

**Comment by dmeehan1968** [comment]
@larsonjj Thanks, but it still seems to be stuck, 16 hours and either its not being run or its not completing.  Is it on a schedule?

**Comment by mathieudutour** [comment]
let's merge this and do the TODO in another PR, that's already a nice improvement

**Pull request merged**
