### PR TITLE
Add shadowInner style to docs

### PR DESCRIPTION
**Pull request by macintoshhelper**
Add `shadowInner` to `styling.md` docs README.

Code reference: https://github.com/airbnb/react-sketchapp/blob/cee20156d3795c3e4899e746aafde7cd22a149e6/src/jsonUtils/style.ts#L89

**Related issues/PRs**

> #160

### CODE REVIEW

**Comment by mathieudutour** [comment]
Maybe, because it's a sketch specific style field, it should be in its own section? This section is more like the list of the RN properties that are(n't) supported by react-sketchapp.
What do you think?

**Comment by macintoshhelper** [comment]
👍 Was thinking of that. Should I move `shadowSpread` too, since that's not supported by React Native?

**Comment by mathieudutour** [comment]
Ah yep good catch

**Comment by macintoshhelper** [comment]
I moved the shadows to a new shadow section (instead of layout), to mirror the React Native docs, and added a note of `react-sketchapp` only ones. Or maybe it would make more sense to have a `react-sketchapp` section?

**Comment by mathieudutour** [comment]
Perfect, thanks

**Comment by macintoshhelper** [comment]
Np, thanks for cleaning up the file/text. I had left in extra spacing in the table for stylistic purposes to keep the width aligned for GitHub, but the website GitBook makes the tables full width anyway, so looks good 🙂.

**Pull request merged**
